# Generated by Django 4.2.23 on 2026-02-07 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TranslatableContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Anahtar')),
                ('label', models.CharField(blank=True, help_text='Admin listesinde görünsün diye kısa açıklama', max_length=200, verbose_name='Açıklama (admin)')),
                ('content_tr', models.TextField(blank=True, verbose_name='İçerik (Türkçe)')),
                ('content_en', models.TextField(blank=True, verbose_name='İçerik (İngilizce)')),
                ('content_de', models.TextField(blank=True, verbose_name='İçerik (Almanca)')),
            ],
            options={
                'verbose_name': 'Çevrilebilir içerik',
                'verbose_name_plural': 'Çevrilebilir içerikler',
                'ordering': ['slug'],
            },
        ),
    ]
