# Generated by Django 4.2.23 on 2026-02-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_seed_fransiz_askisi_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ad Soyad')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('phone', models.CharField(max_length=50, verbose_name='Telefon')),
                ('subject', models.CharField(blank=True, max_length=200, verbose_name='Konu')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('kvkk', models.BooleanField(default=True, verbose_name='KVKK onayı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Gönderim tarihi')),
                ('source', models.CharField(blank=True, help_text='Örn. contact, home, api', max_length=20, verbose_name='Kaynak')),
            ],
            options={
                'verbose_name': 'İletişim formu gönderisi',
                'verbose_name_plural': 'İletişim formu gönderileri',
                'ordering': ['-created_at'],
            },
        ),
    ]
