# Generated by Django 4.2.23 on 2026-02-08 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_content_only_fransiz_askisi'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(default='Op. Dr. Mustafa Öksüz', max_length=200, verbose_name='Doktor adı')),
                ('phone', models.CharField(default='+90 540 740 40 77', max_length=30, verbose_name='Telefon')),
                ('whatsapp', models.CharField(default='905407404077', max_length=30, verbose_name='WhatsApp (ülke kodu ile, başında + yok)')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-posta')),
                ('address', models.TextField(blank=True, verbose_name='Adres')),
                ('footer_copyright', models.CharField(default='Tüm hakları saklıdır.', max_length=200, verbose_name='Footer telif metni')),
                ('instagram_url', models.URLField(blank=True, default='https://www.instagram.com/doctor.mustafaoksuz/', verbose_name='Instagram URL')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook URL')),
                ('developer_credit', models.CharField(blank=True, help_text='Örn: Bu site X tarafından geliştirilmiştir.', max_length=200, verbose_name='Geliştirici notu (footer)')),
            ],
            options={
                'verbose_name': 'Genel bilgiler',
                'verbose_name_plural': 'Genel bilgiler',
            },
        ),
        migrations.CreateModel(
            name='AboutContent',
            fields=[
            ],
            options={
                'verbose_name': 'Hakkımızda içeriği',
                'verbose_name_plural': 'Hakkımızda içerikleri',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('website.translatablecontent',),
        ),
        migrations.CreateModel(
            name='BotoksContent',
            fields=[
            ],
            options={
                'verbose_name': 'Botoks içeriği',
                'verbose_name_plural': 'Botoks içerikleri',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('website.translatablecontent',),
        ),
        migrations.CreateModel(
            name='ContactContent',
            fields=[
            ],
            options={
                'verbose_name': 'İletişim içeriği',
                'verbose_name_plural': 'İletişim içerikleri',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('website.translatablecontent',),
        ),
        migrations.CreateModel(
            name='DolguContent',
            fields=[
            ],
            options={
                'verbose_name': 'Dolgu içeriği',
                'verbose_name_plural': 'Dolgu içerikleri',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('website.translatablecontent',),
        ),
        migrations.CreateModel(
            name='FransizAskisiContent',
            fields=[
            ],
            options={
                'verbose_name': 'Fransız Askısı içeriği',
                'verbose_name_plural': 'Fransız Askısı içerikleri',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('website.translatablecontent',),
        ),
        migrations.CreateModel(
            name='HomeContent',
            fields=[
            ],
            options={
                'verbose_name': 'Anasayfa içeriği',
                'verbose_name_plural': 'Anasayfa içerikleri',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('website.translatablecontent',),
        ),
        migrations.CreateModel(
            name='MezoterapiContent',
            fields=[
            ],
            options={
                'verbose_name': 'Mezoterapi içeriği',
                'verbose_name_plural': 'Mezoterapi içerikleri',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('website.translatablecontent',),
        ),
        migrations.CreateModel(
            name='PrpContent',
            fields=[
            ],
            options={
                'verbose_name': 'PRP içeriği',
                'verbose_name_plural': 'PRP içerikleri',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('website.translatablecontent',),
        ),
        migrations.CreateModel(
            name='RinoplastiContent',
            fields=[
            ],
            options={
                'verbose_name': 'Rinoplasti içeriği',
                'verbose_name_plural': 'Rinoplasti içerikleri',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('website.translatablecontent',),
        ),
    ]
