# Generated by Django 4.2.23 on 2026-02-08 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_seed_all_page_contents'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=80, unique=True, verbose_name='Anahtar')),
                ('image', models.ImageField(blank=True, help_text='Yüklemezseniz statik varsayılan görsel kullanılır.', null=True, upload_to='site_images/%Y/%m/', verbose_name='Görsel')),
                ('label', models.CharField(blank=True, max_length=200, verbose_name='Açıklama (admin)')),
            ],
            options={
                'verbose_name': 'Site görseli',
                'verbose_name_plural': 'Site görselleri',
                'ordering': ['key'],
            },
        ),
    ]
