# Generated by Django 4.2.23 on 2026-02-25 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_seed_about_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='JinekomastiContent',
            fields=[
            ],
            options={
                'verbose_name': 'Jinekomasti içeriği',
                'verbose_name_plural': 'Jinekomasti içerikleri',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('website.translatablecontent',),
        ),
        migrations.CreateModel(
            name='MemeEstetigiContent',
            fields=[
            ],
            options={
                'verbose_name': 'Meme Estetiği içeriği',
                'verbose_name_plural': 'Meme Estetiği içerikleri',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('website.translatablecontent',),
        ),
        migrations.CreateModel(
            name='VucutEstetigiContent',
            fields=[
            ],
            options={
                'verbose_name': 'Vücut Estetiği içeriği',
                'verbose_name_plural': 'Vücut Estetiği içerikleri',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('website.translatablecontent',),
        ),
        migrations.CreateModel(
            name='YuzEstetigiContent',
            fields=[
            ],
            options={
                'verbose_name': 'Yüz Estetiği içeriği',
                'verbose_name_plural': 'Yüz Estetiği içerikleri',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('website.translatablecontent',),
        ),
        migrations.AddField(
            model_name='siteimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Görsel değiştiğinde cache busting için kullanılır.', verbose_name='Son güncelleme'),
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='siteimage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='instagram_url',
            field=models.URLField(blank=True, default='https://www.instagram.com/plasticsurgeon.mustafaoksuz/', verbose_name='Instagram URL'),
        ),
        migrations.AlterField(
            model_name='translatablecontent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
