# Generated by Django 5.2.1 on 2025-06-09 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, verbose_name='Ad Soyad')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(max_length=16, verbose_name='Telefon')),
                ('subject', models.CharField(max_length=200, verbose_name='Konu')),
                ('message', models.TextField(max_length=500, verbose_name='Mesaj')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Gönderilme Tarihi')),
                ('is_read', models.BooleanField(default=False, verbose_name='Okundu mu?')),
            ],
            options={
                'verbose_name': 'İletişim Formu',
                'verbose_name_plural': 'İletişim Formları',
                'ordering': ['-created_at'],
            },
        ),
    ]
