# Sayfa içerikleri – admin'de düzenlenebilir (sadece içerik metinleri). Başlıklar şablonda.

FRANSIZ_ASKISI_DEFAULTS = {
    "hero_subtitle": "Emilir ipliklerle doğal yüz germe ve sıkılaştırma. Ameliyatsız çözüm.",
    "about_lead": "Fransız askısı (PDO Thread Lift), emilir iplikler kullanılarak yapılan ameliyatsız yüz germe ve sıkılaştırma işlemidir.",
    "about_paragraph": "Bu yöntemde kullanılan PDO (Polydioxanone) iplikleri cerrahi operasyonlarda da kullanılan güvenli materyallerdir. İplikler cilt altına yerleştirilerek sarkan dokuları yukarı çeker ve kolajen üretimini artırır.",
    "about_thread_types_title": "Ek Faydaları",
    "about_thread_1": "Anında germe ve sıkılaştırma etkisi",
    "about_thread_2": "Doğal kolajen üretimi ile uzun süreli sonuç",
    "about_thread_3": "Minimal risk, kısa iyileşme süresi",
    "about_thread_4": "Kişiye özel tedavi planı",
    "process_step_1_desc": "Yüz analizi yapılır ve uygun iplik türü belirlenir. Sarkan bölgeler ve tedavi planı değerlendirilir.",
    "process_step_2_desc": "Cilt temizlenir ve lokal anestezi uygulanır. İplik giriş noktaları işaretlenir.",
    "process_step_3_desc": "30-60 dakika süren uygulama. İnce kanüller ile iplikler cilt altına yerleştirilir.",
    "process_step_4_desc": "Hafif ödem ve morarmalar normaldir. Anında germe etkisi görülür ve günlük hayata dönülür.",
    "process_step_5_desc": "2-4 hafta içinde kolajen üretimi artar. Final etki 2-3 ayda tam olarak görülür.",
    "process_step_6_desc": "Etki 12-18 ay sürer. İplikler tamamen emilir, kolajen etkisi devam eder.",
    "benefits_lead": "Fransız askısı ameliyatsız yüz germenin en etkili yöntemidir. Hem anında germe hem de uzun süreli kolajen üretimi sağlar.",
    "benefit_1_desc": "Uygulama sonrası hemen lifting etkisi",
    "benefit_2_desc": "Abartısız, doğal germe etkisi",
    "benefit_3_desc": "Uzun süreli cilt yenilenmesi",
    "benefit_4_desc": "Emilir PDO iplikler, minimal risk",
    "faq_1_q": "Fransız askısı ağrılı mıdır?",
    "faq_2_q": "Fransız askısı etkisi ne kadar sürer?",
    "faq_3_q": "PDO iplikler güvenli midir?",
    "faq_4_q": "İşlem sonrası ne zaman normale dönerim?",
    "faq_5_q": "Hangi yaşta fransız askısı yapılabilir?",
    "faq_1_a": "İşlem lokal anestezi altında yapılır, bu nedenle ağrı hissedilmez. Uygulama sonrası hafif gerginlik hissi olabilir ancak ağrı kesici gerektirecek kadar ağrılı değildir.",
    "faq_2_a": "İplik etkisi 12-18 ay sürer. İplikler tamamen emildikten sonra bile, uyardığı kolajen üretimi sayesinde cilt kalitesi uzun süre korunur.",
    "faq_3_a": "PDO iplikler uzun yıllardır cerrahide kullanılan güvenli materyallerdir ve vücut tarafından emilir.",
    "faq_4_a": "Ertesi gün normal hayatınıza dönebilirsiniz; sadece birkaç gün ağır mimikten ve bir hafta ağır spordan kaçınmanız önerilir.",
    "faq_5_a": "Genellikle 30 yaş üzeri hastalarda uygundur; esas belirleyici olan cilt sarkma derecesi ve beklentilerdir.",
    "cta_section_lead": "Fransız askısı ile ilgili tüm sorularınızı yanıtlayalım",
    "cta_disclaimer": "Konsültasyonunuz tamamen ücretsiz ve yükümlülük gerektirmez",
}

# Anasayfa – hero ve hakkımda bölümü metinleri
HOME_DEFAULTS = {
    "hero_lead": "15 yıllık deneyim ve son teknoloji ile plastik cerrahi alanında size en iyi hizmeti sunuyoruz. Güvenilir ve estetik sonuçlar için bizimle iletişime geçin.",
    "about_lead": "15 yıllık deneyimim ile plastik ve rekonstrüktif cerrahi alanında uzmanlaştım. Hastalarımın güvenliğini ve memnuniyetini her şeyin önünde tutarak, en güncel tekniklerle doğal ve estetik sonuçlar elde etmeyi hedefliyorum.",
}

# Hakkımızda – mesleki deneyim paragrafları
ABOUT_DEFAULTS = {
    "experience_1": "2018 yılından itibaren İzmir Özel Gazi Hastanesi'nde özellikle meme estetiği, meme dikleştirme, meme protezi ile büyütme, burun estetiği, liposuction, karın germe, jinekomasti, yüz ve boyun germe, üst ve alt göz kapağı estetiği, şakak germe, dermal dolgu, dudak dolgusu ve botoks uygulamaları başta olmak üzere yoğun şekilde estetik cerrahi operasyonları yapmaktadır. Halen Özel İzmir Gazi Hastanesi'nde estetik cerrahi operasyonlar ile botoks/dolgu uygulamaları gerçekleştirmektedir. Özel Aydın Medinova Hastaneleri'ndeki görevi 2025'te sona ermiştir.",
    "experience_2": "Türk Plastik Cerrahi Derneği Yeterlilik (Board Sınavı) Belgesine sahiptir. Türk Plastik Cerrahi Derneği ve Estetik Plastik Cerrahi Derneği'nin tam üyesidir. Halen Türk Plastik Cerrahi Derneği Saç Ekimi Bilim Kurulu üyesi olup, Ekim 2020-2022 yılları arasında Türk Tabipleri Birliği İzmir Hekim Meclisi'nde delegelik görevini yürütmüştür. Evli ve 3 çocuk babasıdır.",
}

# İletişim – sayfa giriş metni (opsiyonel)
CONTACT_DEFAULTS = {
    "intro": "Randevu ve bilgi için aşağıdaki formu doldurabilir veya doğrudan iletişime geçebilirsiniz.",
}

# Rinoplasti
RINOPLASTI_DEFAULTS = {
    "about_lead": "Rinoplasti, burun estetiği olarak da bilinen, burnun şeklini ve işlevini iyileştirmek için yapılan cerrahi bir işlemdir.",
    "about_paragraph": "Modern rinoplasti tekniklerinde amaç, hastanın yüz yapısına en uygun, doğal görünümlü bir burun elde etmektir. Sadece estetik kaygılarla değil, nefes alma problemlerinin çözümü için de uygulanabilir.",
    "process_step_1_desc": "Detaylı muayene ve 3D simülasyon ile ameliyat planlaması yapılır. Beklentileriniz ve tıbbi durumunuz değerlendirilir.",
    "process_step_2_desc": "Gerekli tetkikler yapılır. Ameliyat günü ve sonrasına dair detaylı bilgilendirme alırsınız.",
    "process_step_3_desc": "1-2 saat süren ameliyat genel anestezi altında gerçekleştirilir. Modern kapalı teknik kullanılır.",
    "process_step_4_desc": "7-10 gün burun teli ile koruma. Düzenli kontroller ile iyileşme süreci takip edilir.",
    "process_step_5_desc": "3-6 ayda şekil oturur, 1 yılda final sonuç elde edilir. Yaşam boyu garanti verilir.",
    "process_step_6_desc": "Düzenli kontroller ile iyileşme süreci izlenir. 7/24 iletişim desteği sağlanır.",
    "benefits_lead": "Rinoplasti sadece estetik bir işlem değil, aynı zamanda işlevsel sorunları da çözen kapsamlı bir cerrahi müdahaledir.",
    "benefit_1_desc": "Yüz ile uyumlu, doğal görünümlü burun şekli",
    "benefit_2_desc": "Septum deviasyonu ve burun tıkanıklığı çözümü",
    "benefit_3_desc": "Kişisel memnuniyet ve sosyal güven artışı",
    "benefit_4_desc": "Yaşam boyu sürecek doğal ve estetik görünüm",
    "faq_1_q": "Rinoplasti ameliyatı ağrılı mıdır?",
    "faq_2_q": "Ne zaman normal hayatıma dönebilirim?",
    "faq_3_q": "Sonuç ne zaman tam olarak belli olur?",
    "faq_4_q": "Rinoplasti ameliyatının riskleri nelerdir?",
    "faq_5_q": "Fiyat nedir ve ne kadar sürer?",
    "faq_1_a": "Rinoplasti ameliyatı genel anestezi altında yapıldığı için ameliyat sırasında hiçbir ağrı hissetmezsiniz. Ameliyat sonrası ağrı çok minimal düzeydedir ve verilen ağrı kesicilerle rahatça kontrol edilebilir.",
    "faq_2_a": "Ofis işi yapıyorsanız 7-10 gün sonra işinize dönebilirsiniz. Ağır spor ve fiziksel aktiviteler için 6-8 hafta beklemeniz gerekir. Sosyal aktivitelere 2 hafta sonra katılabilirsiniz.",
    "faq_3_a": "Rinoplasti kalıcı bir işlemdir. Burun yaşam boyu yeni şeklini korur; ek ameliyat sadece travma veya özel istek durumunda gündeme gelir.",
    "faq_4_a": "Genel anestezi kullanılır; ameliyat sırasında hiçbir şey hissetmezsiniz. Ameliyat sonrası ilk günlerde hafif ağrı olabilir, ağrı kesicilerle kontrol edilir.",
    "faq_5_a": "Ameliyat 1-2 saat sürer. Hastanede genellikle 1 gece kalınır, ertesi gün taburcu edilirsiniz.",
    "cta_section_lead": "Rinoplasti ile ilgili tüm sorularınızı yanıtlayalım",
    "cta_disclaimer": "Konsültasyonunuz tamamen ücretsiz ve yükümlülük gerektirmez",
}

# Dolgu
DOLGU_DEFAULTS = {
    "about_lead": "Dolgu uygulamaları, hyaluronik asit gibi güvenli maddelerle yüzün çeşitli bölgelerine hacim kazandırma, şekillendirme ve yaşlanma belirtilerini azaltma işlemidir.",
    "about_paragraph": "Bu uygulamalar sayesinde dudaklar dolgunlaştırılabilir, yanak kontuları belirginleştirilebilir, çene hatları şekillendirilebilir ve çeşitli yaşlanma çizgileri doldurulabilir. Sonuçlar anında görülür ve doğal görünür.",
    "process_step_1_desc": "Yüz analizi yapılır ve uygun dolgu türü belirlenir. Beklentiler ve uygulama planı değerlendirilir.",
    "process_step_2_desc": "Cilt temizlenir ve topikal anestezi uygulanır. Enjeksiyon noktaları işaretlenir.",
    "process_step_3_desc": "20-45 dakika süren uygulama. Hassas tekniklerle doğal görünüm elde edilir.",
    "process_step_4_desc": "Hafif ödem ve kızarıklık normal. Sonuç anında görülür ve günlük hayata dönülür.",
    "process_step_5_desc": "1-2 hafta içinde ödem geçer ve final şekil alır. Doğal görünüm elde edilir.",
    "process_step_6_desc": "Etki 9-18 ay sürer. Düzenli kontroller ve gerekirse yenileme uygulaması yapılır.",
    "benefits_lead": "Dolgu uygulamaları güvenli, etkili ve anında sonuç veren ameliyatsız estetik çözümlerdir. Doğal görünüm elde etmenin en pratik yoludur.",
    "benefit_1_desc": "Uygulama sonrası hemen görünür etki",
    "benefit_2_desc": "Abartısız, doğal hacim artışı",
    "benefit_3_desc": "FDA onaylı, biyouyumlu dolgu",
    "benefit_4_desc": "9-18 ay süren kalıcı sonuç",
    "faq_1_q": "Dolgu uygulaması ağrılı mıdır?",
    "faq_2_q": "Dolgu etkisi ne kadar sürer?",
    "faq_3_q": "Dolgu güvenli midir?",
    "faq_4_q": "Dolgu beğenmezsem ne olur?",
    "faq_5_q": "Dolgu sonrası ne zaman normale dönerim?",
    "faq_1_a": "İşlem topikal krem veya lokal anestezi ile yapılır. Hafif batma hissi olabilir, ağrı minimal düzeydedir.",
    "faq_2_a": "Etki 9-18 ay sürer; dolgu türüne ve uygulama bölgesine göre değişir. Düzenli uygulama ile uzun süre korunabilir.",
    "faq_3_a": "Hyaluronik asit dolgular FDA onaylı ve vücut tarafından zamanla emilir. Alerji riski çok düşüktür.",
    "faq_4_a": "Ertesi gün normal hayatınıza dönebilirsiniz. Birkaç gün ağır mimik ve masajdan kaçınmanız önerilir.",
    "faq_5_a": "Dudak, yanak, çene, burun kökü, nazolabial çizgiler ve el dorsumu gibi birçok bölgeye uygulanabilir.",
    "cta_section_lead": "Dolgu uygulamaları ile ilgili tüm sorularınızı yanıtlayalım",
    "cta_disclaimer": "Konsültasyonunuz tamamen ücretsiz ve yükümlülük gerektirmez",
}

# Botoks
BOTOKS_DEFAULTS = {
    "about_lead": "Botoks, yüzdeki kırışıklıkları azaltmak ve önlemek için kullanılan, klinik olarak kanıtlanmış güvenli bir uygulamadır.",
    "about_paragraph": "Botulinum toksin enjeksiyonu, mimik kaslarını geçici olarak gevşeterek kaş çatma çizgileri, alın kırışıklıkları ve göz çevresi kırışıklıklarını yumuşatır. Uygulama 10-15 dakika sürer ve anında günlük hayata dönülür.",
    "process_step_1_desc": "Yüz analizi ve hedeflenen bölgeler belirlenir. Beklentileriniz değerlendirilir.",
    "process_step_2_desc": "Cilt temizlenir. Gerekirse topikal anestezi uygulanır.",
    "process_step_3_desc": "İnce iğnelerle hedef bölgelere enjeksiyon yapılır. İşlem 10-15 dakika sürer.",
    "process_step_4_desc": "Hafif kızarıklık veya küçük morluklar olabilir. Birkaç gün içinde kaybolur.",
    "process_step_5_desc": "3-7 gün içinde etki belirginleşir. 2 haftada tam sonuç görülür.",
    "process_step_6_desc": "Etki 3-6 ay sürer. Düzenli uygulama ile daha uzun süre korunabilir.",
    "benefits_lead": "Botoks, ameliyatsız kırışıklık tedavisinde en çok tercih edilen yöntemdir. Hızlı, güvenli ve doğal sonuç verir.",
    "benefit_1_desc": "Kaş çatma ve alın kırışıklıklarında belirgin azalma",
    "benefit_2_desc": "Göz çevresi (kaz ayağı) kırışıklıklarının yumuşaması",
    "benefit_3_desc": "Önleyici tedavi ile yeni kırışıklıkların geciktirilmesi",
    "benefit_4_desc": "Hızlı uygulama, kısa iyileşme süresi",
    "faq_1_q": "Botoks uygulaması ağrılı mıdır?",
    "faq_2_q": "Botoks etkisi ne kadar sürer?",
    "faq_3_q": "Botoks güvenli midir?",
    "faq_4_q": "Botoks sonrası ne zaman normal hayatıma dönebilirim?",
    "faq_5_q": "Hangi yaşta botoks yapılabilir?",
    "faq_1_a": "İşlem ince iğnelerle yapılır; çoğu hastada anestezi gerekmez. Hafif batma hissi olabilir.",
    "faq_2_a": "Etki 3-6 ay sürer. Düzenli uygulama ile süre uzayabilir.",
    "faq_3_a": "Botoks on yıllardır kullanılan, FDA onaylı güvenli bir üründür. Doğru doz ve teknikle yan etki riski çok düşüktür.",
    "faq_4_a": "Aynı gün makyaj yapılabilir; 6 saat yüzü yıkamamanız ve masaj yapmamanız önerilir.",
    "faq_5_a": "Alın, kaş arası ve göz çevresi en sık uygulama bölgeleridir. Boyun ve çene bölgesi de uygulanabilir.",
    "cta_section_lead": "Botoks uygulaması ile ilgili tüm sorularınızı yanıtlayalım",
    "cta_disclaimer": "Konsültasyonunuz tamamen ücretsiz ve yükümlülük gerektirmez",
}

# Mezoterapi
MEZOTERAPI_DEFAULTS = {
    "hero_motto": "Cilt Yenileme,\nMezoterapi ile Mümkün",
    "hero_subtitle": "Vitamin, mineral ve aktif maddelerle cilt gençleştirme. İşlem sadece 15-30 dakika sürer.",
    "about_lead": "Mezoterapi, cilt ve saç problemlerini tedavi etmek için vitamin, mineral ve hyaluronik asit gibi maddelerin ince iğnelerle cilt altına uygulandığı bir yöntemdir.",
    "about_paragraph": "Yüz mezoterapisi cildi nemlendirir, canlılık kazandırır ve ince kırışıklıkları azaltır. Saç mezoterapisi ise saç dökülmesini yavaşlatır ve saç kalitesini artırır. Uygulama 15-30 dakika sürer.",
    "process_step_1_desc": "Cilt veya saç analizi yapılır. Uygun kokteyl ve bölgeler belirlenir.",
    "process_step_2_desc": "Cilt temizlenir. Gerekirse topikal anestezi uygulanır.",
    "process_step_3_desc": "İnce iğnelerle küçük dozlar halinde uygulama yapılır. 15-30 dakika sürer.",
    "process_step_4_desc": "Hafif kızarıklık ve küçük kabarcıklar normaldir. Birkaç saat içinde geçer.",
    "process_step_5_desc": "Birkaç seans sonrası cilt parlaklığı ve nem artar. Saçta 2-3 ay içinde etki görülür.",
    "process_step_6_desc": "Düzenli seanslarla sonuçlar kalıcı hale getirilebilir. Önerilen aralık 2-4 hafta.",
    "benefits_lead": "Mezoterapi hem cilt hem saç için doğal, ameliyatsız bir tedavi seçeneğidir. Minimal risk ve kısa iyileşme süresi sunar.",
    "benefit_1_desc": "Cilt nemi ve parlaklığında artış",
    "benefit_2_desc": "İnce kırışıklıkların azalması",
    "benefit_3_desc": "Saç dökülmesinin yavaşlaması",
    "benefit_4_desc": "Kolajen ve elastin uyarımı",
    "faq_1_q": "Mezoterapi ağrılı mıdır?",
    "faq_2_q": "Kaç seans gerekir?",
    "faq_3_q": "Mezoterapi etkisi ne kadar sürer?",
    "faq_4_q": "Mezoterapi güvenli midir?",
    "faq_5_q": "Hangi bölgelere uygulanır?",
    "faq_1_a": "İnce iğneler kullanılır; çoğu hastada tolere edilebilir. Topikal anestezi ile rahatlık sağlanabilir.",
    "faq_2_a": "Cilt için 4-6 seans, saç için 8-10 seans önerilir. Aralık 2-4 hafta olabilir.",
    "faq_3_a": "Evet. Mezoterapi doğal maddeler kullanır; alerji öyküsüne göre içerik ayarlanır.",
    "faq_4_a": "Aynı gün makyaj yapılabilir. Birkaç saat güneşten ve sıcaktan kaçınmanız önerilir.",
    "faq_5_a": "Yüz, boyun, dekolte, saçlı deri ve el dorsumu en sık uygulama bölgeleridir.",
    "cta_section_lead": "Mezoterapi ile ilgili tüm sorularınızı yanıtlayalım",
    "cta_disclaimer": "Konsültasyonunuz tamamen ücretsiz ve yükümlülük gerektirmez",
}

# PRP
PRP_DEFAULTS = {
    "about_lead": "PRP (Platelet Rich Plasma), kendi kanınızdan elde edilen trombosit zengin plazmanın cilt veya saç bölgesine enjekte edildiği yenileyici bir tedavidir.",
    "about_paragraph": "Trombositler büyüme faktörleri içerir; bu da ciltte kolajen üretimini artırır, saç foliküllerini güçlendirir. Tamamen doğal ve kişiye özel bir yöntemdir. Yüz gençleştirme, saç dökülmesi ve cilt kalitesi artırmada kullanılır.",
    "process_step_1_desc": "Kan alınır ve özel tüplerde santrifüj edilir. PRP ayrıştırılır.",
    "process_step_2_desc": "Cilt veya saçlı deri temizlenir. Uygulama bölgeleri belirlenir.",
    "process_step_3_desc": "PRP ince iğnelerle cilt altına veya saçlı deriye uygulanır. 20-30 dakika sürer.",
    "process_step_4_desc": "Hafif kızarıklık ve şişlik normaldir. 1-2 gün içinde azalır.",
    "process_step_5_desc": "2-4 hafta içinde ciltte parlaklık ve sıkılık artar. Saçta 2-3 ay içinde etki görülür.",
    "process_step_6_desc": "3-4 seanslık kür önerilir. Yılda bir tekrar ile sonuçlar korunabilir.",
    "benefits_lead": "PRP tamamen kendi kanınızdan üretildiği için alerji riski yoktur. Cilt ve saç için doğal yenilenme sağlar.",
    "benefit_1_desc": "Ciltte kolajen artışı ve sıkılaşma",
    "benefit_2_desc": "Saç kalitesi ve yoğunluğunda artış",
    "benefit_3_desc": "Doğal, kişiye özel tedavi",
    "benefit_4_desc": "Minimal risk, kısa iyileşme süresi",
    "faq_1_q": "PRP tedavisi ağrılı mıdır?",
    "faq_2_q": "PRP kaç seans gerektirir?",
    "faq_3_q": "PRP güvenli midir?",
    "faq_4_q": "PRP sonrası iyileşme nasıldır?",
    "faq_5_q": "PRP hangi bölgelere uygulanır?",
    "faq_1_a": "Önce kolunuzdan az miktarda kan alınır. PRP ayrıştırıldıktan sonra ince iğnelerle uygulama yapılır. Hafif batma hissi olabilir.",
    "faq_2_a": "Cilt için 3-4 seans, saç için 4-6 seans önerilir. Aralık 3-4 hafta olabilir.",
    "faq_3_a": "Evet. Kendi kanınızdan elde edildiği için alerji ve red reaksiyonu riski yoktur.",
    "faq_4_a": "1-2 gün hafif kızarıklık olabilir. Makyaj ertesi gün yapılabilir.",
    "faq_5_a": "Yüz, boyun, dekolte, el dorsumu ve saçlı deri en sık uygulama bölgeleridir.",
    "cta_section_lead": "PRP tedavisi ile ilgili tüm sorularınızı yanıtlayalım",
    "cta_disclaimer": "Konsültasyonunuz tamamen ücretsiz ve yükümlülük gerektirmez",
}

# Meme Estetiği
MEME_ESTETIGI_DEFAULTS = {
    "about_lead": "Meme estetiği, kadınların meme boyutu, şekli ve simetrisini iyileştirmek için yapılan cerrahi işlemlerdir.",
    "about_paragraph": "Meme büyütme, küçültme, dikleştirme ve şekillendirme gibi farklı tekniklerle kişinin vücut yapısına en uygun, doğal ve estetik sonuçlar elde edilir.",
    "process_step_1_desc": "3D simülasyon ile meme analizi yapılır. İstenen boyut ve şekil hakkında detaylı planlama gerçekleştirilir.",
    "process_step_2_desc": "Gerekli tetkikler ve mamografi yapılır. İmplant seçimi ve ameliyat tekniği belirlenir.",
    "process_step_3_desc": "2-3 saat süren ameliyat genel anestezi altında yapılır. Minimal iz tekniği kullanılır.",
    "process_step_4_desc": "1-2 hafta özel sütyen kullanımı. Düzenli kontroller ile iyileşme süreci takip edilir.",
    "process_step_5_desc": "3-6 ayda final şekil alır. Doğal ve estetik görünüm elde edilir.",
    "process_step_6_desc": "Düzenli kontroller ile implant durumu izlenir. 7/24 destek hizmeti verilir.",
    "benefits_lead": "Meme estetiği, kadınların kendilerini daha güzel ve özgüvenli hissetmelerini sağlayan önemli bir cerrahi dalıdır.",
    "benefit_1_desc": "Doğal ve feminen görünüm",
    "benefit_2_desc": "İdeal vücut proporsiyonu",
    "benefit_3_desc": "Kişisel memnuniyet ve mutluluk",
    "benefit_4_desc": "Daha rahat giyim seçenekleri",
    "faq_1_q": "Meme büyütme ameliyatı ağrılı mıdır?",
    "faq_2_q": "İmplantlar ne kadar süre dayanır?",
    "faq_3_q": "Emzirme üzerinde etkisi var mı?",
    "faq_4_q": "Ameliyat izleri görünür olur mu?",
    "faq_5_q": "Ne zaman spor yapabilirim?",
    "faq_1_a": "Ameliyat genel anestezi altında yapıldığı için hiçbir ağrı hissetmezsiniz. Ameliyat sonrası ağrı minimal düzeydedir ve verilen ağrı kesicilerle kontrol edilir.",
    "faq_2_a": "Modern silikon implantlar 15-20 yıl veya daha uzun süre kullanılabilir. Düzenli kontrollerle implant durumu takip edilir.",
    "faq_3_a": "Doğru teknikle yapılan meme büyütme ameliyatı emzirmeyi etkilemez. Meme dokusuna zarar verilmeden işlem gerçekleştirilir.",
    "faq_4_a": "İzler meme altı kıvrımında veya meme başı çevresinde gizlenir. 6-12 ay içinde izler neredeyse görünmez hale gelir.",
    "faq_5_a": "Hafif aktivitelere 2 hafta sonra, ağır spora 6-8 hafta sonra başlayabilirsiniz. Yüzme gibi aktiviteler için 4-6 hafta beklemeniz gerekir.",
    "cta_section_lead": "Meme estetiği ile ilgili tüm sorularınızı yanıtlayalım",
    "cta_disclaimer": "Konsültasyonunuz tamamen ücretsiz ve yükümlülük gerektirmez",
}

# Yüz Estetiği
YUZ_ESTETIGI_DEFAULTS = {
    "about_lead": "Yüz estetiği (face lift), yüzdeki yaşlanma belirtilerini gidermek ve genç görünümü yeniden kazandırmak için yapılan cerrahi işlemlerdir.",
    "about_paragraph": "Yaşla birlikte yüz derisinde oluşan sarkma, kırışıklık ve hacim kaybı gibi sorunları düzelterek doğal ve genç bir görünüm elde edilir.",
    "process_step_1_desc": "Yüz analizi ve 3D simülasyon ile kişiye özel ameliyat planı hazırlanır.",
    "process_step_2_desc": "Gerekli tetkikler yapılır. Ameliyat günü ve sonrası için detaylı bilgilendirme verilir.",
    "process_step_3_desc": "3-5 saat süren ameliyat genel anestezi altında yapılır. Modern endoskopik teknikler kullanılır.",
    "process_step_4_desc": "2-3 hafta özel bakım gerekir. Düzenli kontroller ile iyileşme süreci takip edilir.",
    "process_step_5_desc": "6 ayda net sonuç görülür, 1 yılda final şekil alır.",
    "process_step_6_desc": "Düzenli kontroller ile sonuç kalitesi korunur.",
    "benefits_lead": "Yüz estetiği, yaşlanma sürecini tersine çeviren ve kendinizi en iyi hissetmenizi sağlayan kapsamlı bir gençleşme çözümüdür.",
    "benefit_1_desc": "Yaşına uygun, doğal ve çekici görünüm",
    "benefit_2_desc": "10-15 yıl süren kalıcı sonuçlar",
    "benefit_3_desc": "Kendinizi genç ve dinamik hissetme",
    "benefit_4_desc": "Saç içi ve doğal kıvrımlarda gizli kesiler",
    "faq_1_q": "Yüz estetiği ağrılı bir işlem midir?",
    "faq_2_q": "Ne zaman normal aktivitelerime dönebilirim?",
    "faq_3_q": "Yüz estetiği sonuçları ne kadar sürer?",
    "faq_4_q": "Ameliyat izleri görünür olur mu?",
    "faq_5_q": "Hangi yaşta yüz estetiği yaptırabilirim?",
    "faq_1_a": "Ameliyat genel anestezi altında yapıldığı için hiçbir ağrı hissetmezsiniz.",
    "faq_2_a": "Hafif aktivitelere 1 hafta sonra, iş hayatına 2-3 hafta sonra dönebilirsiniz.",
    "faq_3_a": "Genellikle 10-15 yıl sürer.",
    "faq_4_a": "Modern tekniklerle izler saç içinde ve kulak çevresindeki doğal kıvrımlarda gizlenir.",
    "faq_5_a": "Genellikle 40-60 yaş aralığında yapılır.",
    "cta_section_lead": "Yüz estetiği ile ilgili tüm sorularınızı yanıtlayalım",
    "cta_disclaimer": "Konsültasyonunuz tamamen ücretsiz ve yükümlülük gerektirmez",
}

# Vücut Estetiği
VUCUT_ESTETIGI_DEFAULTS = {
    "about_lead": "Vücut estetiği, vücudun çeşitli bölgelerindeki şekil bozukluklarını düzelterek ideal vücut konturlarını elde etmeyi amaçlayan cerrahi işlemlerdir.",
    "about_paragraph": "Liposuction, karın germe, kalça-bacak germe, kol germe gibi farklı tekniklerle vücudun estetik görünümü iyileştirilir.",
    "process_step_1_desc": "Vücut analizi ve 3D simülasyon ile kişiye özel ameliyat planı hazırlanır.",
    "process_step_2_desc": "Gerekli tetkikler yapılır. Ameliyat tekniği ve beklentiler detaylı olarak görüşülür.",
    "process_step_3_desc": "2-4 saat süren ameliyat genel anestezi altında yapılır.",
    "process_step_4_desc": "2-4 hafta özel korse kullanımı. Düzenli kontroller ile iyileşme süreci takip edilir.",
    "process_step_5_desc": "3-6 ayda ideal vücut konturu elde edilir.",
    "process_step_6_desc": "Düzenli kontroller ile sonuç kalitesi korunur.",
    "benefits_lead": "Vücut estetiği, sadece görünümü iyileştirmekle kalmaz, aynı zamanda kişinin yaşam kalitesini ve özgüvenini de artırır.",
    "benefit_1_desc": "Orantılı ve estetik vücut konturu",
    "benefit_2_desc": "Daha rahat hareket ve aktivite",
    "benefit_3_desc": "Kişisel memnuniyet ve sosyal güven",
    "benefit_4_desc": "Daha geniş giyim seçenekleri",
    "faq_1_q": "Vücut estetiği ameliyatı ağrılı mıdır?",
    "faq_2_q": "Ne zaman normal aktivitelerime dönebilirim?",
    "faq_3_q": "Vücut estetiği sonuçları kalıcı mıdır?",
    "faq_4_q": "Ameliyat izleri görünür olur mu?",
    "faq_5_q": "Hangi yaşta vücut estetiği yaptırabilirim?",
    "faq_1_a": "Ameliyat genel anestezi altında yapıldığı için hiçbir ağrı hissetmezsiniz.",
    "faq_2_a": "Hafif aktivitelere 1 hafta sonra, ofis işine 2 hafta sonra dönebilirsiniz.",
    "faq_3_a": "Evet, sonuçlar kalıcıdır. Sağlıklı yaşam tarzı sürdürmek önemlidir.",
    "faq_4_a": "Modern tekniklerle izler mümkün olduğunca gizli yerlerde yapılır.",
    "faq_5_a": "18 yaş üstü herkes vücut estetiği yaptırabilir.",
    "cta_section_lead": "Vücut estetiği ile ilgili tüm sorularınızı yanıtlayalım",
    "cta_disclaimer": "Konsültasyonunuz tamamen ücretsiz ve yükümlülük gerektirmez",
}

# Jinekomasti
JINEKOMASTI_DEFAULTS = {
    "about_lead": "Jinekomasti, erkeklerde göğüs dokusunun normalden büyük olması durumudur. Bu durum hormonal değişiklikler, yaş, ilaç kullanımı veya genetik faktörler nedeniyle oluşabilir.",
    "about_paragraph": "Jinekomasti sadece estetik bir sorun değil, aynı zamanda erkeklerin özgüvenini olumsuz etkileyen psikolojik bir durumdur.",
    "process_step_1_desc": "Göğüs dokusu analizi ve jinekomasti tipinin belirlenmesi. Gerekirse hormonal testler yapılır.",
    "process_step_2_desc": "Uygun tedavi yönteminin seçimi. Anestezi türü belirlenir.",
    "process_step_3_desc": "1-2 saat süren ameliyat. Minimal iz bırakan teknikler kullanılır.",
    "process_step_4_desc": "1-2 hafta özel yelek kullanımı. Düzenli kontroller ile iyileşme süreci takip edilir.",
    "process_step_5_desc": "3-6 ayda ideal göğüs konturu elde edilir. Doğal ve maskülen görünüm sağlanır.",
    "process_step_6_desc": "Düzenli kontroller ile sonucun kalıcılığı sağlanır.",
    "benefits_lead": "Jinekomasti tedavisi sadece estetik bir düzeltme değil, aynı zamanda erkeklerin yaşam kalitesini artıran önemli bir müdahaledir.",
    "benefit_1_desc": "Doğal ve erkeksi göğüs konturu",
    "benefit_2_desc": "Sosyal hayata daha rahat katılım",
    "benefit_3_desc": "Her türlü kıyafeti rahatça giyebilme",
    "benefit_4_desc": "Yüzme ve spor aktivitelerinde rahatlık",
    "faq_1_q": "Jinekomasti ameliyatı ağrılı mıdır?",
    "faq_2_q": "Ne zaman normale dönebilirim?",
    "faq_3_q": "Jinekomasti tekrar oluşur mu?",
    "faq_4_q": "Ameliyat izleri görünür olur mu?",
    "faq_5_q": "Hangi yaşta jinekomasti ameliyatı olabilirim?",
    "faq_1_a": "Ameliyat anestezi altında yapıldığı için hiçbir ağrı hissetmezsiniz.",
    "faq_2_a": "İşinize 3-5 gün sonra dönebilirsiniz. Ağır spordan 4-6 hafta kaçınmanız gerekir.",
    "faq_3_a": "Doğru teknikle yapılan ameliyat sonrası nüks oranı çok düşüktür.",
    "faq_4_a": "Modern tekniklerle kesiler meme başı çevresinde gizli yerlerde yapılır.",
    "faq_5_a": "Genellikle 18 yaş üstü hastalar ameliyat olabilir.",
    "cta_section_lead": "Jinekomasti ile ilgili tüm sorularınızı yanıtlayalım",
    "cta_disclaimer": "Konsültasyonunuz tamamen ücretsiz ve yükümlülük gerektirmez",
}
